export EDITOR=code

export HISTFILE=~/.zhistory
export HISTSIZE=10000
export SAVEHIST=10000

export CERTIFICATE_BUNDLE=~/.ssl/zscaler-bundle.pem
export REQUESTS_CA_BUNDLE=$CERTIFICATE_BUNDLE
export CURL_CA_BUNDLE=$CERTIFICATE_BUNDLE
export NODE_EXTRA_CA_CERTS=$CERTIFICATE_BUNDLE
export AWS_CA_BUNDLE=$CERTIFICATE_BUNDLE
export SSL_CERT_FILE=$CERTIFICATE_BUNDLE


